# Generated by Django 2.2 on 2020-01-21 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendreq_friendreqacp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_req', models.CharField(default='no', max_length=3)),
                ('frnds', models.CharField(default='no', max_length=3)),
                ('auser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_acp', to=settings.AUTH_USER_MODEL)),
                ('ruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_req', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='friendreqacp',
            name='auser',
        ),
        migrations.DeleteModel(
            name='FriendReq',
        ),
        migrations.DeleteModel(
            name='FriendReqAcp',
        ),
    ]
